defaults:
  - settings_schema

_tags_: ~

dataset: CIFAR100
epochs: 100
optimizer: SGD
learning_rate: 1.0
momentum: ~
milestones:
  30: 0.1
  80: 0.1
batchnorm: True
scenario: INC_TASK
offline: False
strategy: Naive

ewc_lambda: 100
ewc_mode: "separate"
ewc_decay: 1.0

lwf_alpha: 1
lwf_temperature: 2

si_lambda: 100

interval:
  robust_accuracy_threshold: 0.9
  robust_lambda: 0.002
  radius_multiplier: 1.0
  max_radius: 1.0
  radius_exponent: 0.5
  scale_init: 5.0
  expansion_learning_rate: 0.1
  normalize_shift: True
  normalize_scale: False
  contraction_epochs: 10