defaults:
  - settings_schema

dataset: CIFAR100

_tags_: ~

epochs: 150

optimizer: SGD
learning_rate: 0.1
momentum: ~
milestones:
  30: 0.1
  100: 0.1
  125: 0.1
scenario: INC_CLASS
offline: False
strategy: Naive