defaults:
  - settings_schema

dataset: CIFAR100

_tags_: ~

epochs: 200

optimizer: SGD
learning_rate: 0.1
momentum: ~
milestones: ~
scenario: INC_CLASS
offline: False
strategy: Interval

interval:
  robust_accuracy_threshold: 0.9
  robust_lambda: 0.002
  radius_multiplier: 1.0
  max_radius: 1.0
  radius_exponent: 0.5
  scale_init: 5.0
  expansion_learning_rate: 0.1
  normalize_shift: True
  normalize_scale: False
  contraction_epochs: 25