defaults:
  - settings_schema

dataset: CIFAR100

_tags_: ~

epochs: 100

optimizer: SGD
learning_rate: 0.01
momentum: ~
scenario: INC_TASK
strategy: Interval

interval:
  robust_accuracy_threshold: 0.75
  robust_lambda: 0.002
  radius_multiplier: 1.0
  max_radius: 1.0
  radius_exponent: 0.5
  scale_init: 5.0
  expansion_learning_rate: 0.01
  normalize_shift: True
  normalize_scale: False
